curso/curso/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'curso.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

curso/urls.py
#!env/bin/python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'curso.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^encuestas/', include('encuestas.urls', namespace="encuestas")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
)

# Texto para poner al final del <title> de cada página.
admin.site.site_title = u'Administración del sitio cursoweb'

# Texto a poner en los <h1> de todas las páginas.
admin.site.site_header = u'Administrador de Curso Web'

# Texto a poner arriba de la página de index del admin
admin.site.index_title = u'Panel de control de Curso Web'

encuestas/urls.py
# -*- coding: utf-8 -*-
from django.views.generic import DetailView, ListView
from encuestas.models import Pregunta, Noticia
from django.conf.urls import patterns, url

from encuestas import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^noticias/$', ListView.as_view(model=Noticia), name='noticias'),
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Pregunta,),
        name='detalle'),


    url(r'^(?P<pk>\d+)/resultados/$', views.ResultadosView.as_view(), 
        name='resultados'),
    url(r'^(?P<pregunta_id>\d+)/votar/$', views.votar, name='votar'),
)

curso/encuestas/models.py
# -*- coding: utf-8 -*-

import datetime

from django.db import models
from django.utils import timezone

class Pregunta(models.Model):
    texto_pregunta = models.CharField(max_length=200)
    pub_date = models.DateTimeField('fecha publicada')    

    def __unicode__(self):              # __str__ en Python 3
        return self.texto_pregunta

    def fue_publicada_recientemente(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)



class Eleccion(models.Model):
    pregunta = models.ForeignKey(Pregunta)
    texto_opcion = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __unicode__(self):              # __str__ en Python 3
        return self.texto_opcion

encuestas/models.py
# -*- coding: utf-8 -*-

import datetime

from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, ResizeToFit

class Pregunta(models.Model):
    texto_pregunta = models.CharField(max_length=200)
    pub_date = models.DateTimeField('fecha publicada')

    def __unicode__(self):              # __str__ en Python 3
        return self.texto_pregunta

    def fue_publicada_recientemente(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    fue_publicada_recientemente.admin_order_field = 'pub_date'
    fue_publicada_recientemente.boolean = True
    fue_publicada_recientemente.short_description = 'Publicada recientemente?'


class Eleccion(models.Model):
    pregunta = models.ForeignKey(Pregunta)
    texto_opcion = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __unicode__(self):              # __str__ en Python 3
        return self.texto_opcion

    class Meta:
        verbose_name_plural = "elecciones"


class Noticia(models.Model):
    titulo = models.CharField(max_length=200)
    contenidos = RichTextField()

    imagen = models.ImageField(upload_to='noticias', null=True, blank=True)

    imagen_thumbnail = ImageSpecField(source='imagen',
                                      processors=[ResizeToFill(50, 50)],
                                      format='JPEG',
                                      options={'quality': 60})
    imagen_principal = ImageSpecField(source='imagen',
                                      processors=[ResizeToFit(800)],
                                      format='JPEG',
                                      options={'quality': 80})

    def __unicode__(self):              # __str__ en Python 3
        return self.titulo

curso/encuestas/views.py
from django.shortcuts import render

# Create your views here.

encuestas/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from encuestas.models import Eleccion, Pregunta


class IndexView(generic.ListView):
    template_name = 'encuestas/index.html'
    context_object_name = 'lista_ultimas_preguntas'

    def get_queryset(self):
        """Retorna las ultimas 5 preguntas."""
        return Pregunta.objects.order_by('-pub_date')[:5]

class ResultadosView(generic.DetailView):
    model = Pregunta
    template_name = 'encuestas/resultados.html'



def votar(request, pregunta_id):
    p = get_object_or_404(Pregunta, pk=pregunta_id)
    try:
        opcion_elegida = p.eleccion_set.get(pk=request.POST['eleccion'])
    except (KeyError, Eleccion.DoesNotExist):
        # Volver a mostrar el formulario para votar.
        return render(request, 'encuestas/detalle.html', {
            'pregunta': p,
            'error_message': u"No seleccionaste una opción.",
        })
    else:
        opcion_elegida.votos += 1
        opcion_elegida.save()
        # siempre retornar un HttpResponseRedirect después de lidiar
        # exitosamente con datos de POST. Esto evita que los datos sean
        # posteados 2 veces si el usuario presiona el botón de Atrás.
        return HttpResponseRedirect(reverse('encuestas:resultados', args=(p.id,)))

encuestas/templates/encuestas/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'encuestas/estilos.css' %}" />

{% if lista_ultimas_preguntas %}
    <ul>
    {% for pregunta in lista_ultimas_preguntas %}
        
        <li><a href="{% url 'encuestas:detalle' pregunta.id %}">{{ pregunta.texto_pregunta }}</a></li>
        
    {% endfor %}
    </ul>
{% else %}
    <p>No hay encuestas disponibles.</p>
{% endif %}

encuestas/templates/encuestas/noticia_list.html
<h1>Noticias</h1>
{% for noticia in object_list %}
    <article>
        <h2>{{ noticia.titulo }}</h1>
            {% if noticia.imagen %}<img src="{{ noticia.imagen_principal.url }}">{% endif %}
        <div>{{ noticia.contenidos|safe }}</div>
    </article>
{% endfor %}

encuestas/templates/encuestas/pregunta_detail.html
<h1>{{ pregunta.texto_pregunta }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'encuestas:votar' pregunta.id %}" method="post">
{% csrf_token %}
{% for eleccion in pregunta.eleccion_set.all %}
    <input type="radio" name="eleccion" id="eleccion{{ forloop.counter }}" 
        value="{{ eleccion.id }}" />
    <label for="eleccion{{ forloop.counter }}">
        {{ eleccion.texto_opcion }}
    </label><br />
{% endfor %}
<input type="submit" value="Votar" />
</form>

encuestas/templates/encuestas/resultados.html
<h1>{{ pregunta.texto_pregunta }}</h1>

<ul>
{% for opcion in pregunta.eleccion_set.all %}
    <li>{{ opcion.texto_opcion }} -- 
        {{ opcion.votos }} voto{{ opcion.votos|pluralize }}
    </li>
{% endfor %}
</ul>

<a href="{% url 'encuestas:detalle' pregunta.id %}">Votar de nuevo?</a>